# Generated by Django 4.0.4 on 2022-05-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='фио клиента')),
                ('phone', models.CharField(max_length=150, null=True, verbose_name='телефон клиента')),
                ('utmSource', models.CharField(max_length=150, null=True, verbose_name='utmSource')),
                ('utmMedium', models.CharField(max_length=150, null=True, verbose_name='utmMedium')),
                ('utmContent', models.CharField(max_length=150, null=True, verbose_name='utmContent')),
                ('utmCampaign', models.CharField(max_length=150, null=True, verbose_name='utmCampaign')),
                ('utmTerm', models.CharField(max_length=150, null=True, verbose_name='utmTerm')),
            ],
        ),
    ]
