# Generated by Django 4.0.4 on 2022-05-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPage', '0002_applications_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='email',
            field=models.CharField(max_length=150, null=True, verbose_name='email'),
        ),
    ]
